server:
  port: ${PORT:8080}

spring:
  application:
    name: booking-service

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    addresses: ${RABBITMQ_URL}
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ASGARDEO_ISSUER_URI}