server:
  port: 8083

spring:
  application:
    name: grid-service

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?user=postgres.zeuzxasnrhlhrcfvlegd&password=Shashika_616
    username: postgres
    password: Shashika_616

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    addresses: amqps://slwalesk:AQ7_tKw1W6Ov4Od2doeZEouHTteJ5j5Q@kingfisher.lmq.cloudamqp.com/slwalesk
    listener:
      simple:
        acknowledge-mode: manual # We want manual ACKs here too!
        retry:
          enabled: true
          max-attempts: 3

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://api.asgardeo.io/t/org88nz1/oauth2/token